version: "3"
services:
    dob-nginx:
        restart: always
        image: nginx:1.23
        ports:
            - "80:80"
        volumes:
            - ./site:/var/www/html:ro
            - ./nginx/conf/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - default
    dob-php:
        restart: always
        build: ./php
        volumes:
            - ./site:/var/www/html:ro
        networks:
            - default
    dob-mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: 1q2w3e4r
        restart: always
        command: --init-file /docker-entrypoint-initdb.d/init.sql
        volumes:
            - ./mysql/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "3306:3306"
        networks:
            - default 
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: dob-mysql
            PMA_USER: root
            PMA_PASSWORD: 1q2w3e4r
        ports:
            - "8081:80"
        restart: always
        networks:
            - default

